### ISSUE TITLE
Property boundaries service is down on prod-2

### ISSUE THREAD

**Issue by rogup** [DigitalCommons/property-boundaries-service#16]
The PBS is down on prod-2, which means properties and visible on LX.

This broke, since we ran an old Ansible playbook on prod-2 when deploying the CWM, which deleted MySql config.

Also, it looks like Uptime Kuma didn't pick up on this outage, since it doesn't check an API route that depends on a DB connection

# Solution

- [x] Re-run the newer playbook (on [this branch](https://github.com/DigitalCommons/technology-and-infrastructure/tree/property-boundaries-service-issue-11)) on prod-2
- [x] Change the URL that Uptime Kuma hits so that it picks up these outages
- [x] Long-term fix: Merge that branch into master ([this PR](https://github.com/DigitalCommons/technology-and-infrastructure/pull/102)) so that we don't keep overwriting the PBS config

**Comment by rogup** [comment]
@lin-d-hop This is now back up and running, and I've sent @wu-lee the PR to review, so that we don't accidentally do this again

**Comment by wu-lee** [comment]
What was broken?

**Comment by ColmDC** [comment]
I am not sure this fix was sufficient. See my thread on Devops-notifications in Element.

"[Property Boundary Service (Prod)] [✅ Up] 200 - OK
colm.massey
This suggests it is back again, but when I try using LX it is still not working. 
Now it is down again, according to Kuma. So my attempting to use it via LX is doing something different to what the kuma query on its own is doing. And it kills the service for a while."

![Image](https://github.com/user-attachments/assets/c18f9c5b-1fab-4ae9-be48-3c9e76995bcd)

**Comment by lin-d-hop** [comment]
Yeah this is still down for me too.
Can we escalate this fix? It's been almost 2 weeks now

**Comment by rogup** [comment]
The fixes for this are now deployed to both staging and production.

I've also re-enabled Uptime Kuma and checked that a repeat of the original problem (the app user being unable to access the MySQL database) is flagged by devops_bot.

So I think this issue is ready close if you're happy with it @ColmDC / @lin-d-hop
